using LoocERP.Data;
using LoocERP.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace LoocERP.Seeders
{
    public static class EmployeeSeeder
    {

        public static async Task Seed(UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager, ApplicationDBContext _context)
        {




            await userManager.CreateAsync(new AppUser
            {
                Id = "1a7b1444-e2c4-4421-9480-617d4cc09c0f",
                UserName = "8740131a-ce67-4e37-93e0-cb1f26d8fe31",
                PhoneNumber = "",
                FirstName = "DANILO",
                LastName = "ALOI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "LAODNL78E06M208E",
                Nazione = "Italia",
                Citta = "LAMEZIA TERME",
                Provincia = "CZ",
                Indirizzo = "VIALE STAZIONE - 9",
                TipoPatente = "B",
                Cap = "88046",
                //CodiceDipendente ="EST084",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "0409cf43-e5a6-4ed0-b25c-ac0d41ec0776",
                UserName = "629c52a8-78ba-49ff-9e77-210d8f1b749f",
                PhoneNumber = "3457259237",
                FirstName = "EDOARDO",
                LastName = "ANDREOLI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "NDRDRD89T09A773J",
                Nazione = "Italia",
                Citta = "ACQUAPPESA",
                Provincia = "CS",
                Indirizzo = "VIA PANTANA - 18",
                TipoPatente = "",
                Cap = "87020",
                //CodiceDipendente ="EST086",
                IBAN = "",
                //ScadenzaDocumento"09/12/2024",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "0666b1ed-2562-47ce-9d31-d550bbeb607d",
                UserName = "49f75109-8c16-483d-bf56-e7ded371cfcb",
                PhoneNumber = "3496493208",
                FirstName = "LORIS",
                LastName = "BELLINI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "BLLLRS65T25Z112C",
                Nazione = "Italia",
                Citta = "REGGIO DI CALABRIA",
                Provincia = "RC",
                Indirizzo = "VIA BOSCHICELLO - 10",
                TipoPatente = "B",
                Cap = "89100",
                //CodiceDipendente ="EST 311",
                IBAN = "",
                //ScadenzaDocumento"25/12/2024",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "c6bc2efe-af68-42b9-a4cc-9d925f5fa005",
                UserName = "8e0510ae-ee93-4d58-836c-ecf222578d24",
                PhoneNumber = "3405607354",
                FirstName = "CARMELO PASQUALE",
                LastName = "BIANCO ",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "BNCCML93A31A773E",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA GAUDIMARE - 4",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST323",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "03607c0a-9f0d-481a-a5ef-01cfe2256420",
                UserName = "43c96c8d-90a3-47c7-9202-340901a2166d",
                PhoneNumber = "3283311941",
                FirstName = "FRANCESCO",
                LastName = "BOZZO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "BZZFNC68L17G317V",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA DEL GRILLO - 14",
                TipoPatente = "",
                Cap = "87027",
                //CodiceDipendente ="EST405",
                IBAN = "",
                //ScadenzaDocumento"17/07/2028",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "9f0625b6-e5b9-40c2-b70b-1297aae49c1d",
                UserName = "c85972ef-e512-4ec5-a262-110b0b910d70",
                PhoneNumber = "3407692064",
                FirstName = "ATTILIO",
                LastName = "BRUNO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "BRNTTL83L17G317A",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "SAN GIOVANNI - ",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST151",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "d2207363-2045-4590-801c-a77910061b91",
                UserName = "42d0f88f-0794-496d-9dcb-09088ab7bf18",
                PhoneNumber = "3890451768",
                FirstName = "GIUSEPPE",
                LastName = "BRUNO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "BRNGPP94M26A773W",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA SAN GIOVANNI - ",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST181",
                IBAN = "",
                //ScadenzaDocumento"26/08/2026",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "8ca14c29-3d69-4e1c-acad-01287e3415db",
                UserName = "d5439579-50bb-44cd-ada5-8caeea678c86",
                PhoneNumber = "3472686567",
                FirstName = "FRANCESCO",
                LastName = "CALVANO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CLVFNC94P07C588K",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA DELLE ROSE - 11",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST324",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "cb5b8399-677b-42cb-b8a7-ecd9ecb5a25e",
                UserName = "971c12ea-47ac-4a77-920d-2a6d6d8eaab2",
                PhoneNumber = "3405374981",
                FirstName = "GIUSEPPE",
                LastName = "CARNEVALE",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CRNGPP92A05A773E",
                Nazione = "Italia",
                Citta = "FUSCALDO",
                Provincia = "CS",
                Indirizzo = "VIA IOVINO - 21",
                TipoPatente = "B",
                Cap = "87024",
                //CodiceDipendente ="EST089",
                IBAN = "",
                //ScadenzaDocumento"05/01/2026",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "ba5fbdbb-7ad3-4b55-b62a-6e888f9717f0",
                UserName = "9af01a04-54ee-4606-8c94-4965e4db624c",
                PhoneNumber = "3293845887",
                FirstName = "MASSIMO",
                LastName = "CARNEVALE",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CRNMSM69S28Z133O",
                Nazione = "Italia",
                Citta = "FUSCALDO",
                Provincia = "CS",
                Indirizzo = "CONTRADA IMMACOLATA - 28",
                TipoPatente = "B",
                Cap = "87024",
                //CodiceDipendente ="EST090",
                IBAN = "",
                //ScadenzaDocumento"26/07/2021",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "d8dcd4d9-537f-4219-85d5-0243fc06aef4",
                UserName = "32e84523-08c5-4a97-9648-a55a4b19a7b3",
                PhoneNumber = "3931275442",
                FirstName = "LUCA",
                LastName = "CARUSO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CRSLCU92E18G317X",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA LAO - 9",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST325",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "84a81a13-c699-4b35-8d89-df8bfea88162",
                UserName = "01054621-8880-40d4-aefc-c7ad4368d1bc",
                PhoneNumber = "3200778294",
                FirstName = "SANTO",
                LastName = "CARUSO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CRSSNT91T14G317M",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA RIACE - 37",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST109",
                IBAN = "",
                //ScadenzaDocumento"17/01/2022",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "049ad4cb-5b5f-4a1c-9df6-52be086a9286",
                UserName = "0c388504-00c8-4cba-ac97-ec13184ab5da",
                PhoneNumber = "3463370056",
                FirstName = "CESARE",
                LastName = "CESARIO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CSRCSR90P07D086A",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "CONTRADA SAN GIOVANNI - 58",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST 316",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "b07027d3-1317-4c97-8ed8-3f0b6b8a866a",
                UserName = "676a8941-45d4-4b60-b320-72672a0b63c9",
                PhoneNumber = "3497739845",
                FirstName = "MARTINO FRANCESCO",
                LastName = "CESARIO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CSRMTN95S11G317K",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA SAN GIOVANNI - ",
                TipoPatente = "",
                Cap = "87038",
                //CodiceDipendente ="EST385",
                IBAN = "",
                //ScadenzaDocumento"11/11/2027",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "c66f3c36-c722-401f-8091-3ccc3aef30bc",
                UserName = "95601945-f817-49ad-8ec7-58629b329aa5",
                PhoneNumber = "",
                FirstName = "FRANCESCO",
                LastName = "CF VENTURA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "",
                Nazione = "Italia",
                Citta = "",
                Provincia = "",
                Indirizzo = " - ",
                TipoPatente = "",
                Cap = "",
                //CodiceDipendente ="EST035",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "a6f5f405-f043-4ae6-b026-93d6e20f8a7a",
                UserName = "c12bdda7-c207-4f6b-9a44-4a6cf679d7d4",
                PhoneNumber = "3404719505",
                FirstName = "MAURIZIO",
                LastName = "CHILELLI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CHLMRZ79H19G317B",
                Nazione = "Italia",
                Citta = "FALCONARA ALBANESE",
                Provincia = "CS",
                Indirizzo = "VIA POZZUOLO - ",
                TipoPatente = "C",
                Cap = "87030",
                //CodiceDipendente ="EST111",
                IBAN = "",
                //ScadenzaDocumento"19/06/2025",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "af07661c-ab04-4828-ba66-48a4316ef55d",
                UserName = "7ee9a295-9399-4a5f-b065-98130eb27d53",
                PhoneNumber = "3809044524",
                FirstName = "LUCA",
                LastName = "CINNANTI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CNNLCU90D17A773V",
                Nazione = "Italia",
                Citta = "FUSCALDO",
                Provincia = "CS",
                Indirizzo = "VIA CATASCERO SNC - ",
                TipoPatente = "",
                Cap = "87024",
                //CodiceDipendente ="EST197",
                IBAN = "",
                //ScadenzaDocumento"18/09/2017",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "78e036b6-78a1-44c7-a12b-76c02b78389a",
                UserName = "5349d628-c3ab-486e-8b42-79333dfe53b3",
                PhoneNumber = "3473453576",
                FirstName = "ROBERT",
                LastName = "COJOCAR",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CJCRRT96M09Z129V",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "STRADA Z - ",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST198",
                IBAN = "",
                //ScadenzaDocumento"09/08/2019",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "61fb82ba-4fcb-4f6f-9eb6-47729e171a54",
                UserName = "88786b40-4176-410c-a703-73edfe919a3e",
                PhoneNumber = "3291241660",
                FirstName = "GIANFRANCO",
                LastName = "COVELLI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CVLGFR83E11L219G",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA STRADA I - 1/B",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST 220",
                IBAN = "",
                //ScadenzaDocumento"11/05/2023",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "7dc72276-5792-4fa0-aa20-fe7161542ecd",
                UserName = "a810e78d-045a-4345-8639-9a4454282878",
                PhoneNumber = "3913550527",
                FirstName = "CRISTIAN",
                LastName = "CUCCINIELLO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CCCCST96B10G317B",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA DELLE SCUOLE - 11",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST327",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "5d590753-5374-4ace-b904-25d9956e76d8",
                UserName = "b6e99170-6964-4fb1-9930-ed309c63e2af",
                PhoneNumber = "3463784861",
                FirstName = "GIANNI",
                LastName = "CURATOLO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CRTGNN88R04G317U",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "CONTRADA SAN GIOVANNI - ",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST134",
                IBAN = "",
                //ScadenzaDocumento"04/10/2027",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "e51c709d-33a3-4652-b792-f0323a0f2248",
                UserName = "046133d4-943a-4817-9143-ba9bb42f3f48",
                PhoneNumber = "3205308160",
                FirstName = "LEANDRO",
                LastName = "CUZZOCREA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "CZZLDR75L20G317S",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA DEL CANNONE - 41",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST158",
                IBAN = "",
                //ScadenzaDocumento"20/05/2020",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "7f78ea22-dd8b-4bc6-a354-e87f087a14ea",
                UserName = "2ea02aac-41cc-4818-9c37-1f5fe2c9da47",
                PhoneNumber = "3488551756",
                FirstName = "LUCA",
                LastName = "DE LUCA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "DLCLCU91T15G317K",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA CAVOUR - 6",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST115",
                IBAN = "",
                //ScadenzaDocumento"11/07/2021",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "f03c8c94-d43e-4718-9c8e-5fa437a419aa",
                UserName = "78a02f1a-3600-496a-8a5e-d01bb0612051",
                PhoneNumber = "3480043697",
                FirstName = "NATALE",
                LastName = "DE LUCA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "DLCNTL94D27G317N",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "STRADA P - ",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST091",
                IBAN = "",
                //ScadenzaDocumento"27/04/2023",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "0d3e29d0-0432-4b99-8fce-e9ca7bf56a1b",
                UserName = "7d3e7ba0-9996-4cf9-b305-e0e49a0b7a27",
                PhoneNumber = "3485830901",
                FirstName = "MICHELE",
                LastName = "DEL CAMPO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "DLCMHL90D27D086H",
                Nazione = "Italia",
                Citta = "SPEZZANO PICCOLO",
                Provincia = "CS",
                Indirizzo = "VIA ACQUACOPERTA - 19",
                TipoPatente = "B",
                Cap = "87050",
                //CodiceDipendente ="EST329",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "4d6f98e6-06b0-4bc3-92af-c3e2637d08ad",
                UserName = "5fef66e2-4b10-4263-881c-d68c85311813",
                PhoneNumber = "3492402305",
                FirstName = "CESARE",
                LastName = "DI BUONO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "DBNCSR84S10D086T",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "STRADA PROVINCIALE - 98/A",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST344",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "e79c6cd9-d228-4553-8440-fe006ad5100d",
                UserName = "1b3d17aa-90e2-44bd-8082-136a3dd23d12",
                PhoneNumber = "3400894529",
                FirstName = "CARLO",
                LastName = "DI SANTO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "DSNCRL78R23H971N",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA TENIMENTO - 4",
                TipoPatente = "",
                Cap = "87027",
                //CodiceDipendente ="EST 315",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "a06acf76-acdc-4c5d-95c3-a5a27eed15e2",
                UserName = "42408001-e746-4605-9df6-2ced6cf689b7",
                PhoneNumber = "3207708720",
                FirstName = "MARCELLO",
                LastName = "DI SANTO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA LIBERTINI - 55",
                TipoPatente = "",
                Cap = "87038",
                //CodiceDipendente ="EST409",
                IBAN = "",
                //ScadenzaDocumento"04/01/2026",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "201fd7e9-b4ef-4d66-9dcb-a9ffcd05dbc4",
                UserName = "47a27855-8dab-458d-96ad-0621e57452bd",
                PhoneNumber = "3498335570",
                FirstName = "SALVATORE",
                LastName = "DI SANTO ",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "DSNSVT94L16G317M",
                Nazione = "Italia",
                Citta = "FUSCALDO",
                Provincia = "CS",
                Indirizzo = "CONTRADA LAGO SOPRA STRADA - SNC",
                TipoPatente = "B",
                Cap = "87024",
                //CodiceDipendente ="EST 218",
                IBAN = "",
                //ScadenzaDocumento"04/07/2020",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "46b3fb50-b110-4794-83a9-6b36d8510115",
                UserName = "fc5ea62c-63ee-425f-b944-39753fd25754",
                PhoneNumber = "3482940575",
                FirstName = "ENRICO",
                LastName = "ESPOSITO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "SPSNRC84L26G317H",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA ANNUNZIATA - 9",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST395",
                IBAN = "",
                //ScadenzaDocumento"10/09/2018",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "faa98fc8-6ae6-4244-a92f-63d8b6020943",
                UserName = "e8912122-a336-4b7e-865f-ced6e64e6ffb",
                PhoneNumber = "3899919403",
                FirstName = "LORENZO",
                LastName = "FACCHINIERI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "FCCLNZ89H05C588U",
                Nazione = "Italia",
                Citta = "RENDE",
                Provincia = "CS",
                Indirizzo = "VIA ALESSANDRO VOLTA - ",
                TipoPatente = "B",
                Cap = "87036",
                //CodiceDipendente ="EST185",
                IBAN = "",
                //ScadenzaDocumento"05/06/2025",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "a78f1383-3f98-4498-a8b5-7edff12f4fd8",
                UserName = "4dce9017-08a7-40c8-b9de-e3993279d33d",
                PhoneNumber = "3470705603",
                FirstName = "ANTONIO",
                LastName = "FERRARA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "FRRNTN91L03A773M",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA MARINA STAZIONE - 28",
                TipoPatente = "K",
                Cap = "87038",
                //CodiceDipendente ="EST331",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "ab5ba230-eca5-44b1-b155-a032f2838daf",
                UserName = "b9611b18-c7f9-4003-9730-076ff6cf979a",
                PhoneNumber = "3477269329",
                FirstName = "CARMINE ANTONELLO",
                LastName = "FERRARO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "FRRCMN91H13G317T",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA DEL MAGGESE - 2",
                TipoPatente = "",
                Cap = "87027",
                //CodiceDipendente ="EST362",
                IBAN = "",
                //ScadenzaDocumento"13/06/2022",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "44c19a99-8577-4fa7-a0da-1d8922bf04dc",
                UserName = "cbbe4d20-faab-416c-9f3d-9d822973e374",
                PhoneNumber = "3203614419",
                FirstName = "GERARDO",
                LastName = "FERRARO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "FRRGRD82D17H490X",
                Nazione = "Italia",
                Citta = "SAN PIETRO IN GUARANO",
                Provincia = "CS",
                Indirizzo = "VIA COZZO DI MARE - 23",
                TipoPatente = "",
                Cap = "87047",
                //CodiceDipendente ="EST387",
                IBAN = "",
                //ScadenzaDocumento"17/04/2027",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "af5b9c20-5177-4ca3-8f50-bbda11eb03d7",
                UserName = "0289527b-3f94-4a79-8a24-3aad339309df",
                PhoneNumber = "3478949649",
                FirstName = "MIRKO",
                LastName = "FILIPPO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "FLPMRK91S07G317J",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA STRADA PROVINCIALE - 48",
                TipoPatente = "",
                Cap = "87038",
                //CodiceDipendente ="EST199",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "c2fe315b-8581-4acf-a4e6-3d1988b17956",
                UserName = "b43c0c34-84da-4356-9ff7-69f0b89a62e8",
                PhoneNumber = "",
                FirstName = "PASQUALE",
                LastName = "FILIPPO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "FLPPQL71A06G317U",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA ACQUA BIANCA - 140",
                TipoPatente = "",
                Cap = "87038",
                //CodiceDipendente ="EST 317",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "006e2688-f451-4228-babd-b5725020a628",
                UserName = "517b2a45-1121-43eb-989d-8e4e2d60d570",
                PhoneNumber = "3453771554",
                FirstName = "SIMONE",
                LastName = "FILIPPO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "FLPSMN86B27C588G",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "STRADA PROVINCIALE - 48",
                TipoPatente = "",
                Cap = "87038",
                //CodiceDipendente ="EST332",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "3885f88d-1996-46b7-a41a-37c43a47be74",
                UserName = "e1490b70-73b2-4bae-ba90-d4ff5b9bd78d",
                PhoneNumber = "3483342278",
                FirstName = "GIANLUCA",
                LastName = "FRANGELLA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "FRNGLC94L12G317Y",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA REGINA ELENA - 77",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST 216",
                IBAN = "",
                //ScadenzaDocumento"12/07/2023",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "6a52c23e-ad71-44ab-bb07-e6a31b08737b",
                UserName = "412050c8-6b08-4529-91f5-e0d025600bc6",
                PhoneNumber = "3920522284",
                FirstName = "ROSARIO",
                LastName = "FRANGELLA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "FRNRSR94L12G317G",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA REGINA ELENA - 77",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST 217",
                IBAN = "",
                //ScadenzaDocumento"12/07/2023",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "22f6bea6-7d35-4d8a-8083-63e392c8ba4b",
                UserName = "a84955ad-ad1c-47ef-b411-fb77b8d136d9",
                PhoneNumber = "3428672854",
                FirstName = "FRANCESCO",
                LastName = "FRANZESE",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "FRNFNC93R20D086J",
                Nazione = "Italia",
                Citta = "COSENZA",
                Provincia = "CS",
                Indirizzo = "PIAZZA PEPPE GERVASI - 13",
                TipoPatente = "B",
                Cap = "87100",
                //CodiceDipendente ="EST334",
                IBAN = "",
                //ScadenzaDocumento"02/11/2018",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "914e10a9-57f7-4c38-b871-7b938d768c41",
                UserName = "fed738a7-4445-4235-a51c-6748a96eec6f",
                PhoneNumber = "3921556016",
                FirstName = "ROCCO",
                LastName = "IANNI'",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "NNIRCC77R12G288W",
                Nazione = "Italia",
                Citta = "BAGNARA CALABRA",
                Provincia = "RC",
                Indirizzo = "VIA CROCE CERAMIDA - 71",
                TipoPatente = "B",
                Cap = "89011",
                //CodiceDipendente ="EST388",
                IBAN = "",
                //ScadenzaDocumento"12/10/2026",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "e7f02a04-954d-4ebf-be8b-ac21bc0a99cf",
                UserName = "b4306d8d-f70e-4305-a6b7-cbbf6bd09760",
                PhoneNumber = "3935228528",
                FirstName = "ALESSANDRO",
                LastName = "IMPROTO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "MPRLSN95R05G317Z",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "LARGO DEI BRUZI - 2",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST095",
                IBAN = "",
                //ScadenzaDocumento"05/10/2018",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "0a7b11d5-04e1-4402-8c7a-cc49f7f85fd7",
                UserName = "67f54b8b-9de9-40ba-afdc-30c98644d6ba",
                PhoneNumber = "3285909151",
                FirstName = "DANILO",
                LastName = "IORIO GNISCI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "RGNDNL86C28G317U",
                Nazione = "Italia",
                Citta = "FALCONARA ALBANESE",
                Provincia = "CS",
                Indirizzo = "VIA PARADISO - 9",
                TipoPatente = "",
                Cap = "87030",
                //CodiceDipendente ="EST410",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "ca905c6c-77dc-4353-81d8-26dfbe6d2a1f",
                UserName = "c526fde8-9580-4804-ad65-db0919e9f619",
                PhoneNumber = "3475726766",
                FirstName = "ROSARIO",
                LastName = "IORIO GNISCI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "RGNRSR92T16G317I",
                Nazione = "Italia",
                Citta = "FIUMEFREDDO BRUZIO",
                Provincia = "CS",
                Indirizzo = "VIA TRENTO - 10",
                TipoPatente = "B",
                Cap = "87030",
                //CodiceDipendente ="EST389",
                IBAN = "",
                //ScadenzaDocumento"28/03/2021",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "1917a6d3-a80c-49de-be5a-af55f1c061b2",
                UserName = "3a8cb7ea-d9ff-42ed-98ac-400cf7387a2e",
                PhoneNumber = "3469873853",
                FirstName = "GIUSEPPE",
                LastName = "IUSI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "SIUGPP76C17G317H",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "RIONE CROCE - 2",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST193",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "a4cb8279-db66-4d59-9a6b-c672baf82be9",
                UserName = "e2d1f378-9893-4343-9462-37ce03b5036a",
                PhoneNumber = "3483924407",
                FirstName = "ANTONIO",
                LastName = "LANZILLOTTA ",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "LNZNTN96L03A773T",
                Nazione = "Italia",
                Citta = "FUSCALDO",
                Provincia = "CS",
                Indirizzo = "CONTRADA GELSOMINO - 90",
                TipoPatente = "",
                Cap = "87024",
                //CodiceDipendente ="EST 205",
                IBAN = "",
                //ScadenzaDocumento"03/07/2025",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "72f508d1-cb15-4824-91e2-7cdb0238c3ec",
                UserName = "9f374b72-b9c1-4c10-a59a-f11be28496f4",
                PhoneNumber = "3497796962",
                FirstName = "DARIO GIUSEPPE",
                LastName = "LATELLA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "LTLDGS89E13F112P",
                Nazione = "Italia",
                Citta = "REGGIO DI CALABRIA",
                Provincia = "RC",
                Indirizzo = "VIA AUGUSTA PELLARO - 21",
                TipoPatente = "B",
                Cap = "89100",
                //CodiceDipendente ="EST401",
                IBAN = "",
                //ScadenzaDocumento"13/05/2026",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "46fcc308-e182-40b7-8a89-78e70ab2b345",
                UserName = "34305ee2-8d69-4f5c-ba2c-424eb34aea58",
                PhoneNumber = "3491775407",
                FirstName = "LORENZO",
                LastName = "LENTI ",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "LNTLNZ84C03A773X",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA LIBERTINI - SNC",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST097",
                IBAN = "",
                //ScadenzaDocumento"03/03/2024",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "f9b43235-1d90-4f2c-ac22-c5b2f37e4eef",
                UserName = "dd7168b8-572b-4514-984e-cf2dd2fea890",
                PhoneNumber = "3429868359",
                FirstName = "MARIO",
                LastName = "LENTI ",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "LNTMRA81P22G317I",
                Nazione = "Italia",
                Citta = "FIUMEFREDDO BRUZIO",
                Provincia = "CS",
                Indirizzo = "VIALE REGIO - 6",
                TipoPatente = "CQC",
                Cap = "87030",
                //CodiceDipendente ="EST413",
                IBAN = "",
                //ScadenzaDocumento"22/09/2023",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "14aba90f-7f8d-4178-9b92-fed052b2b20a",
                UserName = "02e4d6e7-1006-461d-ae7c-cfbcdd7fb0e3",
                PhoneNumber = "3463318089",
                FirstName = "MARCO FRANCESCO",
                LastName = "LEPORE",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "LPRMCF97M05G317J",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "STRADA PROVINCIALE - ",
                TipoPatente = "",
                Cap = "87038",
                //CodiceDipendente ="EST411",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "3e2b6dd1-6ee1-46bb-87ee-851bc074730c",
                UserName = "b66dac55-ca6a-4b3c-9f9d-8ce8383b95eb",
                PhoneNumber = "3480345777",
                FirstName = "PINO",
                LastName = "LEPORE",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "LPRPNI72M10D086G",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "STRADA PROVINCIALE - 56",
                TipoPatente = "C",
                Cap = "87038",
                //CodiceDipendente ="EST116",
                IBAN = "",
                //ScadenzaDocumento"10/08/2026",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "4d329b74-0b0b-45dc-941b-ee457059b57d",
                UserName = "21cc0767-b22c-4178-96d0-aab700532c67",
                PhoneNumber = "",
                FirstName = "SILVIO",
                LastName = "LONGO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "LNGSLV74A09F708D",
                Nazione = "Italia",
                Citta = "MORANO CALABRO",
                Provincia = "CS",
                Indirizzo = "VIA SELLARO - 11",
                TipoPatente = "B",
                Cap = "87016",
                //CodiceDipendente ="EST0449",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "13183d2e-60b9-46f7-82ed-bdada6997c7f",
                UserName = "3d78a2b0-fbcc-4d8c-a1b5-9ed8abc7baf4",
                PhoneNumber = "3395700718",
                FirstName = "FRANCESCO",
                LastName = "MALITO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "MLTFNC88A28A773U",
                Nazione = "Italia",
                Citta = "FUSCALDO",
                Provincia = "CS",
                Indirizzo = "VIA OLIVETO - 24",
                TipoPatente = "B",
                Cap = "87024",
                //CodiceDipendente ="EST411",
                IBAN = "",
                //ScadenzaDocumento"28/01/2026",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "0a8c8cb5-9e33-48b6-90f1-034237dd00a9",
                UserName = "b5b59122-61dc-4302-9402-3c16986323c6",
                PhoneNumber = "3479963290",
                FirstName = "UGO LUIGINO",
                LastName = "MANDARINO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "MNDGGN86L21G317E",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA POLLELLA  - 169",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST139",
                IBAN = "",
                //ScadenzaDocumento"21/07/2026",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "1c56a7ab-1f4c-4e0d-adf7-26a0c5274337",
                UserName = "843a0baa-051f-49e2-a430-85f9dde328d6",
                PhoneNumber = "3408781642",
                FirstName = "ALESSANDRO",
                LastName = "MANNARINO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "MNNLSN91S14G317G",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA CRISOTOFORO COLOMBO - N.1",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST098",
                IBAN = "",
                //ScadenzaDocumento"04/09/2017",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "631f75a7-294a-42ed-a5da-96fdc8d61a3c",
                UserName = "d80b9bcb-1452-4939-b060-25557b121d39",
                PhoneNumber = "3406946262",
                FirstName = "ALESSIO",
                LastName = "MARCONE",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "MRCLSS90E07G317D",
                Nazione = "Italia",
                Citta = "FUSCALDO",
                Provincia = "CS",
                Indirizzo = "VIA PANTANI LACCARI - 15/A",
                TipoPatente = "B",
                Cap = "87024",
                //CodiceDipendente ="EST336",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "6c1674b9-11ad-41cf-aba8-1451f1242517",
                UserName = "75fa3144-9b43-4dc9-93fd-cda8ff9771fd",
                PhoneNumber = "3284868520",
                FirstName = "GIOVANNI",
                LastName = "MARTINI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "MRTGNN84D12G317Z",
                Nazione = "Italia",
                Citta = "FUSCALDO",
                Provincia = "CS",
                Indirizzo = "VIA PRINCIPALE - 65",
                TipoPatente = "C",
                Cap = "87024",
                //CodiceDipendente ="EST141",
                IBAN = "",
                //ScadenzaDocumento"12/04/2025",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "41c63428-a2ff-4b09-8216-627a277a7029",
                UserName = "5812fe41-e5ca-425a-acdc-52383d19d459",
                PhoneNumber = "3440165923",
                FirstName = "FABIO",
                LastName = "MERISI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "MRSFBA76E29F119E",
                Nazione = "Italia",
                Citta = "GIOIA TAURO",
                Provincia = "RC",
                Indirizzo = "VIA SAN PIO X - 6",
                TipoPatente = "B",
                Cap = "89013",
                //CodiceDipendente ="EST345",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "075d237c-9665-484d-88c0-d51d936b0983",
                UserName = "91fbd5e8-8303-4d65-a7bd-8538519a5992",
                PhoneNumber = "3461744478",
                FirstName = "FEDELE FRANCESCO",
                LastName = "MOLINARO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "MLNFLF88S22G317K",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA CARPINELLE - 10",
                TipoPatente = "",
                Cap = "87027",
                //CodiceDipendente ="EST366",
                IBAN = "",
                //ScadenzaDocumento"26/10/2021",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "208ea622-0ad7-45d0-b7b1-3207cfe4cf0d",
                UserName = "6238cd32-253a-49b1-8e97-46995e47837a",
                PhoneNumber = "3357350562",
                FirstName = "EUGENIO",
                LastName = "MOLINARO NOVELLO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "MLNGNE73S26G317D",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "CONTRADA DEUDA  - 25",
                TipoPatente = "C",
                Cap = "87027",
                //CodiceDipendente ="EST118",
                IBAN = "",
                //ScadenzaDocumento"26/11/2026",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "3db86a52-7f5d-4eda-ac4b-477e2702e786",
                UserName = "c523c099-0afb-45d4-b6a7-1f04ede703e3",
                PhoneNumber = "",
                FirstName = "FILIPPO",
                LastName = "MORRONE",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "MRRFPP64S15D086I",
                Nazione = "Italia",
                Citta = "PEDACE",
                Provincia = "CS",
                Indirizzo = "VIA AMORELLO - 21",
                TipoPatente = "",
                Cap = "87050",
                //CodiceDipendente ="EST412",
                IBAN = "",
                //ScadenzaDocumento"15/11/2024",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "7f6cfaac-59f5-4adc-bf30-a148ba8d35cb",
                UserName = "a567b959-66ee-45c0-99c1-ade455c36343",
                PhoneNumber = "3246116098",
                FirstName = "ALDO",
                LastName = "NOVELLO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "NVLLDA90C24G317B",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA DEL CARMELO - 16",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST339",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "18c068d2-66b3-4ed9-8b0d-f0dcd7e21594",
                UserName = "452164d0-228b-403f-98a8-8fd43cd6a839",
                PhoneNumber = "3884906301",
                FirstName = "GIUSEPPE",
                LastName = "OLIVERIO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "LVRGPP92R24D122F",
                Nazione = "Italia",
                Citta = " CUTRO",
                Provincia = "KR",
                Indirizzo = "SCALO FERROVIARIO SAN LEONARDO - 2",
                TipoPatente = "B",
                Cap = "88842",
                //CodiceDipendente ="EST200",
                IBAN = "",
                //ScadenzaDocumento"16/09/2020",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "240e1dd0-273a-4908-aa25-aae76a7fd912",
                UserName = "6c579768-7e80-43cb-9e35-b400630c7b51",
                PhoneNumber = "3392045834",
                FirstName = "ANDREA",
                LastName = "PANZA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "PNZNDR68T11D086L",
                Nazione = "Italia",
                Citta = "ZUMPANO",
                Provincia = "CS",
                Indirizzo = "VIALE EUROPA - 53",
                TipoPatente = "B",
                Cap = "87040",
                //CodiceDipendente ="EST391",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "d540a036-2937-44b4-8904-44120e42fa48",
                UserName = "68375424-1d9a-49dd-8e40-c095f7ddb044",
                PhoneNumber = "3807404967",
                FirstName = "SALVATORE",
                LastName = "PAPARO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "PPRSVT82P17C352E",
                Nazione = "Italia",
                Citta = "MONTEPAONE",
                Provincia = "CZ",
                Indirizzo = "VIA VOLTURNO - 23",
                TipoPatente = "C",
                Cap = "88060",
                //CodiceDipendente ="EST363",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "85e24bcc-ccc9-4ae1-8058-1ef31bdea64b",
                UserName = "09c50dba-53ed-4dcb-aa84-88d2233bd5ca",
                PhoneNumber = "3408175315",
                FirstName = "ALEXSANDER",
                LastName = "PATERNOSTER",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA TENIMENTO - 4",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST 222",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "95f21fb5-9fe7-44d4-999d-fd4a5bc9da39",
                UserName = "eb873914-4d73-4707-8774-dab65c3773a0",
                PhoneNumber = "3478046255",
                FirstName = "CLAUDIO",
                LastName = "PATITUCCI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "PTTCLD85P17G317R",
                Nazione = "Italia",
                Citta = "FIUMEFREDDO BRUZIO",
                Provincia = "CS",
                Indirizzo = "VIA DEL MULINO - 15",
                TipoPatente = "B",
                Cap = "87030",
                //CodiceDipendente ="EST322",
                IBAN = "",
                //ScadenzaDocumento"17/09/2027",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "a732c17c-2a19-4c04-8014-3f994a8b6d8c",
                UserName = "bd71fc82-708e-489d-993f-e425c2c47cab",
                PhoneNumber = "3481234906",
                FirstName = "SALVATORE",
                LastName = "PERROTTA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "PRRSVT68H28D828X",
                Nazione = "Italia",
                Citta = "FUSCALDO",
                Provincia = "CS",
                Indirizzo = "VIA SERRICELLA - ",
                TipoPatente = "",
                Cap = "87024",
                //CodiceDipendente ="EST408",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "e20b5a3b-e1ed-4b28-aff3-bc2624bf409d",
                UserName = "8da29113-8a3e-49b8-be6d-6b54074dda24",
                PhoneNumber = "3409280391",
                FirstName = "ANTONELLO",
                LastName = "PERRUSO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "PRRNNL81E18G317W",
                Nazione = "Italia",
                Citta = "FALCONARA ALBANESE",
                Provincia = "CS",
                Indirizzo = "VIA PARADISO - 9",
                TipoPatente = "",
                Cap = "87030",
                //CodiceDipendente ="EST392",
                IBAN = "",
                //ScadenzaDocumento"18/05/2021",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "510730a7-862b-4421-b9a6-f62619b0421b",
                UserName = "d1752535-80fc-4753-a761-4528ebca7b8b",
                PhoneNumber = "3280648233",
                FirstName = "MASSIMO",
                LastName = "PETRILLI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "PTRMSM97D21D086A",
                Nazione = "Italia",
                Citta = "MONTALTO UFFUGO",
                Provincia = "CS",
                Indirizzo = "VIA MESCA SNC - ",
                TipoPatente = "B",
                Cap = "87046",
                //CodiceDipendente ="EST346",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "a7a5f103-2bff-4430-97be-21120950c1fb",
                UserName = "a01732de-96d3-4d39-9909-4f0d7c54ad21",
                PhoneNumber = "3453333654",
                FirstName = "FRANCESCO",
                LastName = "POLITANO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "PLTFNC97C17H579Y",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA LARGO SAN DOMENICO - 1",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST 226",
                IBAN = "",
                //ScadenzaDocumento"17/03/2027",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "605471d4-eed4-4535-83d4-5c93f74b7bd2",
                UserName = "bfbd9a60-2d9a-43c9-8736-71d7abd30562",
                PhoneNumber = "3806833301",
                FirstName = "OTTAVIO",
                LastName = "PUGLIESE",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "PGLTTV62C21G317S",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA SAN MICHELE - 20",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST396",
                IBAN = "",
                //ScadenzaDocumento"17/07/2021",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "15fca67d-5c5d-432a-b286-2fa255b720c4",
                UserName = "4bf05d43-e9ff-4371-81d8-37d11cc22ba5",
                PhoneNumber = "3483013972",
                FirstName = "GIUSEPPE",
                LastName = "RAGO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "RGAGPP91T01D086Y",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA LUNGOMARE SUD TRAV.C - 6",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST127",
                IBAN = "",
                //ScadenzaDocumento"02/07/2018",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "0b1a6538-61ce-4771-9e37-bd0d88936b6a",
                UserName = "10a302da-5c3c-44e4-893a-93d071103d25",
                PhoneNumber = "3298916490",
                FirstName = "ANTONIO",
                LastName = "RASO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "RSANTN89L28M208A",
                Nazione = "Italia",
                Citta = "LAMEZIA TERME",
                Provincia = "CZ",
                Indirizzo = "VIA BUCOLIA DI SOPRA - 62",
                TipoPatente = "B",
                Cap = "88046",
                //CodiceDipendente ="EST340",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "95bba070-9954-4b92-8980-2f87923988e0",
                UserName = "b6321ed9-5475-49c7-b04d-d913fa8fa62d",
                PhoneNumber = "",
                FirstName = "FEDERICO",
                LastName = "ROCCA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "RCCFRC88T22M208K",
                Nazione = "Italia",
                Citta = "FALERNA",
                Provincia = "CZ",
                Indirizzo = "VIA TIMPONE  - 14",
                TipoPatente = "",
                Cap = "88042",
                //CodiceDipendente ="EST313",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "58da5498-2929-4606-8558-efd2195aad63",
                UserName = "27845dba-c245-42a4-a08c-c57fdd8eeffb",
                PhoneNumber = "3492926142",
                FirstName = "VITTORIO",
                LastName = "RUSSO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "RSSVTR76S30Z112E",
                Nazione = "Italia",
                Citta = "NOCERA TIRINESE",
                Provincia = "CZ",
                Indirizzo = "VIA MONACELLO - 13",
                TipoPatente = "",
                Cap = "88047",
                //CodiceDipendente ="EST178",
                IBAN = "",
                //ScadenzaDocumento"30/11/2025",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "703876f6-b02b-46d8-b533-f6d252ba3917",
                UserName = "c420ed34-3f2c-455a-9fa8-2c14bfdb25dc",
                PhoneNumber = "3403716062",
                FirstName = "MASSIMO",
                LastName = "SALERNO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "SLRMSM73E29H971Y",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "CORSO C. COLOMBO - 8",
                TipoPatente = "C",
                Cap = "87038",
                //CodiceDipendente ="EST364",
                IBAN = "",
                //ScadenzaDocumento"29/05/2023",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "ab842f8a-4bcf-4174-b9ac-b716c4d86a48",
                UserName = "88ef5950-ad82-4c8f-8dd7-9754f50a8f17",
                PhoneNumber = "3804387205",
                FirstName = "VINCENZO",
                LastName = "SAPONE",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "SPNVCN81M25G317O",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA STRADA A - 46",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST341",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "c7760480-6eb9-4341-91e0-3ce0123c8271",
                UserName = "94c14d1b-0dd7-4103-b89b-993eadf0d26c",
                PhoneNumber = "3493614230",
                FirstName = "FRANCESCO",
                LastName = "SCILLA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "SCLFNC85M31G317R",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "VIA POLLELLA - 163",
                TipoPatente = "",
                Cap = "87038",
                //CodiceDipendente ="EST320",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "c2737335-3229-4ae1-978f-b7fb186a04ef",
                UserName = "32f3cc8b-df6e-41ef-95bb-08cf72f8e903",
                PhoneNumber = "",
                FirstName = "MAURIZIO",
                LastName = "SCRIVANO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "SCRMRZ61H27I896O",
                Nazione = "Italia",
                Citta = "CASOLE BRUZIO",
                Provincia = "CS",
                Indirizzo = "via Francesco di Notar Giovanni - 5",
                TipoPatente = "B",
                Cap = "87050",
                //CodiceDipendente ="EST353",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "6fc46a31-f832-4335-8aae-f307531ac370",
                UserName = "991f764f-513c-45cf-a92c-cac2ecdefca2",
                PhoneNumber = "3467678126",
                FirstName = "AGOSTINO",
                LastName = "SERPA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "SRPGTN88H15G317Y",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA DELLA CICALA - 143",
                TipoPatente = "",
                Cap = "87027",
                //CodiceDipendente ="EST147",
                IBAN = "",
                //ScadenzaDocumento"15/06/2024",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "60fbbe06-1389-466f-9496-75a583e2db66",
                UserName = "24881173-51ca-420b-9329-4ac1b3bfdd80",
                PhoneNumber = "3465134505",
                FirstName = "PASQUALE",
                LastName = "SERPA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "SRPPQL91S06G388X",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA DELLA BADIA - 16",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST 223",
                IBAN = "",
                //ScadenzaDocumento"06/11/2024",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "4bd5ce8d-f75b-4c2f-be9a-6bdb04580e70",
                UserName = "3af0238a-3238-4df5-bec2-ae2f4661a23a",
                PhoneNumber = "3296299175",
                FirstName = "PASQUALE",
                LastName = "TRUSCELLI",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "TRSPQL94C28A773B",
                Nazione = "Italia",
                Citta = "DIAMANTE",
                Provincia = "CS",
                Indirizzo = "VIA ANTONELLO DA MESSINA - 3",
                TipoPatente = "B",
                Cap = "87023",
                //CodiceDipendente ="EST148",
                IBAN = "",
                //ScadenzaDocumento"08/10/2019",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "a02c2c80-807a-4244-8739-df8199ebdb2c",
                UserName = "cc32ef87-9259-475d-b514-6e972d8fa37f",
                PhoneNumber = "3206955187",
                FirstName = "MARCO",
                LastName = "VANZILLOTTA",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "VNZMRC74R03H971J",
                Nazione = "Italia",
                Citta = "SAN LUCIDO",
                Provincia = "CS",
                Indirizzo = "CONTRADA PUPPA - 28",
                TipoPatente = "B",
                Cap = "87038",
                //CodiceDipendente ="EST 227",
                IBAN = "",
                //ScadenzaDocumento"03/10/2024",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "8d1ec984-ae9c-411a-b640-d908ca40676c",
                UserName = "b270f8eb-cb44-4b15-8d9f-f565224eaeef",
                PhoneNumber = "3452699305",
                FirstName = "EMILIO",
                LastName = "VIGILANTE ",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "VGLMLE92L10G317W",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA GIUSTINIANO - 11",
                TipoPatente = "",
                Cap = "87027",
                //CodiceDipendente ="EST318",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "3388f398-4a9c-4eed-b83f-27041f729e5a",
                UserName = "794aa859-acf7-47d0-b6d6-91f94f5df169",
                PhoneNumber = "3458128170",
                FirstName = "LUCA",
                LastName = "ZACCARO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "ZCCLCU89D14G317M",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA DELLA SILA - 2",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST343",
                IBAN = "",
                //ScadenzaDocumento"",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");

            await userManager.CreateAsync(new AppUser
            {
                Id = "77cd67ae-1cb9-4f6e-a38c-e1331115ea32",
                UserName = "b1f333d0-2d72-467d-ba10-9b0c4ad690a1",
                PhoneNumber = "3493455951",
                FirstName = "PIERPAOLO",
                LastName = "ZACCARO",
                isEmployee = 1,
                isExternal = 1,
                CodiceFiscale = "ZCCPPL90R18G317J",
                Nazione = "Italia",
                Citta = "PAOLA",
                Provincia = "CS",
                Indirizzo = "VIA DELLA SILA - 2",
                TipoPatente = "B",
                Cap = "87027",
                //CodiceDipendente ="EST102",
                IBAN = "",
                //ScadenzaDocumento"18/10/2026",
                matricola = "",
                IDCompany = null,
            }, "Produzione.15");




        }
    }
}
